sudo: false
language: node_js
node_js:
  - stable
cache: yarn
script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "true" ]; then commitlint-travis; fi
  - yarn test

after_success:
  - npm run semantic-release
branches:
  only:
    - master
